### ISSUE TITLE
Can not install

### ISSUE THREAD

**Issue by astashko** [dphilipson/typescript-string-enums#13]
When I add typescript-string-enums 0.3.0 to package.json, I receive this error:
npm ERR! cb() never called!
after trying npm install

**Comment by dphilipson** [comment]
Thank you for the report. I'm looking into it.

**Comment by dphilipson** [comment]
Sorry for the inconvenience. Please try again now with version 0.3.1.

**Comment by astashko** [comment]
It works, thanks.
