### ISSUE TITLE
Use Object.entries

### ISSUE THREAD

**Issue by monolithed** [dphilipson/typescript-string-enums#15]
```ts
        for (const prop in e) {
            if (hasOwnProperty(e, prop)) {
                result.push(prop);
            }
        }
```

```ts
        for (const [prop, value] of Object.entries(e)) {
                result.push(prop);
        }
```

I believe the second example looks more elegant

**Comment by dphilipson** [comment]
Hi monolithed,

Unfortunately `Object.entries()` is not supported in all major browsers. In particular, it is absent from Safari on iOS and from Internet Explorer, according to [MDN's page on Object.entries()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/entries).

Actually though, your mentioning this made me realize that it should be using `Object.keys()` instead, so I'll make that change when I have the chance. Thank you!

**Comment by monolithed** [comment]
I believe people know about polyfils.

**Comment by dphilipson** [comment]
Consumers shouldn't need to install a polyfill to use a 40 line library.

**Comment by dphilipson** [comment]
Alright, should be fixed. The new version simply says
```javascript
return Object.keys(e) as Array<keyof T>;
```
