### ISSUE TITLE
How to get key of a enum.

### ISSUE THREAD

**Issue by Rj-s** [dphilipson/typescript-string-enums#21]
I have one situation here :- 

Below is my enum:- 
    
    export const ColorCodes = Enum({
      ES_IN_1: 'RED',
      ES_IN_2: 'YELLOW',
    });

Now i get a string code dynamically from server :- 'ES_IN_1' or 'ES_IN_2' .
I need to compare this string code with enum and need to implement custom code. something like this:- 

    const serverCode  = 'ES_IN_1';

    if(serverCode == ColorCodes.ES_IN_1.toString()){
        ...... custom code.
    }else if(serverCode == ColorCodes.ES_IN_2.toString()){
       ....... custom code.
    }

The problem is how would i get key of this ColorCodes.ES_IN_1 'which is ES_IN_1'.
I dont see something toString() or getKey() here which could resolve this issue. 
 
Thanks

**Comment by dphilipson** [comment]
Hi Rajesh,

The first thing I would ask is whether it makes more sense to have the enum go the other direction, e.g.
``` javascript
export const ColorCodes = Enum({
  RED: 'ES_IN_1',
  YELLOW: 'ES_IN_2',
});
```
in which case your code would be
``` javascript
if (serverCode === ColorCodes.RED) {
  ...
```
It makes more sense to me that `RED` should be the key and `ES_IN_1` should be the value, since `RED` is easier to read when it appears in your code but `ES_IN_1` is the string which has meaning during program execution. In general, I would think of the key as human-readable (like a variable name) and the value as what the machine needs during execution.

But supposing you really do want the enum as written above, you can do the following, which is admittedly a bit unpleasant.
``` javascript
const color = (ColorCodes as any)[serverCode];
if (color === ColorCodes.ES_IN_1) {
    // Do something.
} else if (color === ColorCodes.ES_IN_2) {
    // Do something else.
} else {
    console.log("Unrecognized color code");
}
```
Does that solve the problem?

**Comment by Rj-s** [comment]
Hi, 
Yes, you are right that we can revert the context of enum key and values but cannot do it as we are bound to use it like this only. Though your solution worked.

Thanks :)

**Comment by Rj-s** [comment]
Hi,
I ran into another issue. Your suggestion is comparing enum values, not enum keys.
these are my enums :- 

    export const ColorCodes = Enum({
    ES_IN_1: 'RED',
    ES_IN_2: 'YELLOW',
    ES_IN_3: 'BLUE',
    ES_IN_4: 'YELLOW',
    ES_IN_5: '',
    ES_IN_6: '',
     });
 
    const serverCode = 'ES_IN_5';
    const color = (ColorCodes as any)[serverCode];
    if (color === ColorCodes.ES_IN_5) {
    // Do something.
    } 
    if (color === ColorCodes.ES_IN_6) {
    // Do something else.
    }

    const serverCode1 = 'ES_IN_2';
    const color1 = (ColorCodes as any)[serverCode1];
    if (color1 === ColorCodes.ES_IN_2) {
    // Do something.
    } 
    if (color1 === ColorCodes.ES_IN_4) {
    // Do something else.
    }

In above cases enum values are getting compared so all conditions are true. In my case i want to check enum keys only, not value. Below conditions are same :- 
    
    (ColorCodes as any)['ES_IN_1'] === ColorCodes.ES_IN_1    // here values are getting compared.    
     'RED' === 'RED'

In my case want i need is something :- 

    'ES_IN_1' === ColorCodes.ES_IN_1.getKey()

Please help me in this. I got stuck because of this.

Thanks in advance.

**Comment by dphilipson** [comment]
Can you clarify why you need to do that? The behavior between the snippet I posted and the one you proposed is identical unless there are multiple keys with the same value. Is that a scenario you need to handle?

**Comment by Rj-s** [comment]
Yes, i have multiple keys with same values. In java we could achieve it. But i am looking for some similar case in javascript/typescript.  

I am totally blocked because of this.

**Comment by dphilipson** [comment]
Alright, I understand the problem now. Your proposed syntax `ColorCodes.ES_IN_1.getKey()` is impossible since `ColorCodes.ES_IN_1` is a primitive string which we can't add data to. I could introduce a new function as follows:
``` javascript
// Returns { ES_IN_1: "ES_IN_1", ES_IN_2: "ES_IN_2", ... }
const ColorCodeKeys = Enum.ofKeys(ColorCodes);

if (serverCode === ColorCodeKeys.ES_IN_1) {
    ...
}
```

Can you confirm that this would solve your problem?

**Comment by Rj-s** [comment]
Yes, I think this will resolve my issue. 

I believe here -
      ColorCodeKeys.ES_IN_1 === 'ES_IN_1'

Thanks,

**Comment by dphilipson** [comment]
Fixed via `Enum.ofKeys` in version `0.3.3`. See readme for usage example.
