### ISSUE TITLE
WebPack source-map-loader warning

### ISSUE THREAD

**Issue by neytema** [dphilipson/typescript-string-enums#23]
[`source-map-loader`](https://www.npmjs.com/package/source-map-loader) emits warning when building `typescript-string-enums`

```
WARNING in ./~/typescript-string-enums/dist/index.js
(Emitted value instead of an instance of Error) Cannot find source file '../src/index.ts': Error: Can't resolve '../src/index.ts' in './~/typescript-string-enums/dist'
```

@dphilipson can you add `inlineSources` compilerOption in `tsconfig.json`?

**Comment by dphilipson** [comment]
Thank you for the report @neytema! This should be fixed in 0.3.4.
