### ISSUE TITLE
Mapping enum values to something else

### ISSUE THREAD

**Issue by Offirmo** [dphilipson/typescript-string-enums#8]
I have an Enum and I'm trying to map the values to something else:

```javascript
const UrlCategory = Enum(
	'pro', // .com, .co.xyz, .biz
	'geek', // .net, .io
	'perso', // .me, .name
	'other',
	'special', // not internet, ex. chrome settings, ftp...
)
type UrlCategory = Enum<typeof UrlCategory>

const UrlCategoryColorMapping = {
	UrlCategory.pro: 'blue',
	UrlCategory.geek: 'yellow',
	UrlCategory.perso: 'pink',
	UrlCategory.other: 'green',
	UrlCategory.special: 'black',
}
```

This is refused by the compiler on the ground of syntax error + `error TS1117: An object literal cannot have multiple properties with the same name in strict mode.` 

Do you have any suggestion ?

**Comment by dphilipson** [comment]
Hi Offirmo,

You can get around this using [computed property](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer#Computed_property_names) syntax, e.g.
``` javascript
const UrlCategoryColorMapping = {
	[UrlCategory.pro]: 'blue',
	[UrlCategory.geek]: 'yellow',
	[UrlCategory.perso]: 'pink',
	[UrlCategory.other]: 'green',
	[UrlCategory.special]: 'black',
}
```
Does that solve your problem?

**Comment by Offirmo** [comment]
Thanks for your help ! You are like a master to me :bow:

Meanwhile I experimented with that:
```typescript
const UrlCategoryColorMapping = new Map<UrlCategory, string>([
	[ UrlCategory.pro, 'blue' ],
	[ UrlCategory.geek, 'yellow' ],
	[ UrlCategory.perso, 'pink' ],
	[ UrlCategory.other, 'green' ],
	[ UrlCategory.special, 'black' ],
])
```

**Comment by Offirmo** [comment]
Your solution works. Thanks.

**Comment by Offirmo** [comment]
Just looked at your other repos, and it's a treasure trove of goodness. Thanks for sharing !!

🥇

**Comment by dphilipson** [comment]
Thank you! Really means a lot to hear it.
